### ISSUE TITLE
Is the App initially supposed to run with a white screen? 

### ISSUE THREAD

**Issue by DeerTTV** [ddwebdevv/react-native-pokemon-challenge#1]
Hi there, I am learning React Native and I when I install the dependencies and run the app in the web viewer, I am hit with a white screen.

I know this is a challenge but I not sure if I've done something wrong before I started. 

Thanks :)

![image](https://user-images.githubusercontent.com/107226920/175769535-8aa76f21-c996-417a-b43a-7cba808fe74a.png)

**Comment by ddwebdevv** [comment]
Hello.
Definitely it shouldn't be just a white screen.
So yeah, check again if you did all steps.
Honestly I haven't run it in a while))

**Comment by DeerTTV** [comment]
> Hello. Definitely it shouldn't be just a white screen. So yeah, check again if you did all steps. Honestly I haven't run it in a while))

Is there anything I need to do in regards to the API key, ie .env on root, to get it to run successfully?

**Comment by ddwebdevv** [comment]
@DeerTTV  no, no need api keys or anything. It doesn't work in browser. Need to open in simulator/emulator or real phone
